package dev.globalgoals.domain;

public enum GoalName {
    POVERTY, FAMINE, HEALTH, EDUCATION, GENDER, HYGIENE, ENERGY, JOB, INFRA, INEQUALITY, RESIDENCE, CONSUMPTION, CLIMATE, OCEAN, GROUND, PEACE, PARTNERSHIP
}
